# Generated by Django 5.0.3 on 2024-05-09 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('poultryName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('totalChicken', models.IntegerField()),
                ('startDate', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(upload_to='images/')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('totalChickenFeed', models.IntegerField()),
                ('totalMedicine', models.IntegerField()),
                ('totalBhus', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('totalVaccine', models.IntegerField()),
                ('poultry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhome.poultry')),
            ],
        ),
    ]
