# Generated by Django 5.0.3 on 2024-05-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poultryName', models.CharField(max_length=20)),
                ('totalChicken', models.IntegerField()),
                ('startDate', models.DateField()),
            ],
        ),
    ]
