# Generated by Django 5.0.3 on 2025-03-12 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('poultryName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('totalChicken', models.IntegerField()),
                ('totalDead', models.IntegerField(default=0)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('Closedstatus', models.BooleanField(default=False)),
                ('closedDate', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('closedDate', models.DateField(auto_now_add=True)),
                ('TransportCost', models.IntegerField()),
                ('RatePerKg', models.IntegerField()),
                ('TotalWeight', models.IntegerField()),
                ('TotalAmount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhome.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poultryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhome.poultry')),
            ],
        ),
        migrations.CreateModel(
            name='DeadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDead', models.IntegerField(default=0)),
                ('deadDate', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poultryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhome.poultry')),
            ],
        ),
        migrations.CreateModel(
            name='BillPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(upload_to='images/')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('totalChickenFeed', models.IntegerField()),
                ('totalMedicine', models.IntegerField()),
                ('totalBhus', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('totalVaccine', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('poultryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhome.poultry')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDana', models.IntegerField(default=0)),
                ('totalMedicine', models.IntegerField(default=0)),
                ('totalVaccine', models.IntegerField(default=0)),
                ('totalAmount', models.IntegerField(default=0)),
                ('totalBhus', models.IntegerField(default=0)),
                ('poultryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhome.poultry')),
            ],
        ),
    ]
