# Generated by Django 5.0.3 on 2024-05-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billpost',
            old_name='poultry',
            new_name='poultryName',
        ),
    ]
