# Generated by Django 5.0.3 on 2025-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultry',
            name='RatePerKg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='poultry',
            name='Status',
            field=models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss'), ('None', 'None')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='poultry',
            name='TotalAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='poultry',
            name='TotalWeight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='poultry',
            name='TransportCost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='poultry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
