# Generated by Django 5.0.3 on 2024-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poultry',
            name='id',
        ),
        migrations.AddField(
            model_name='poultry',
            name='poultryId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
