# Generated by Django 5.0.3 on 2024-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0003_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='totalBhus',
            field=models.IntegerField(default=0),
        ),
    ]
