# Generated by Django 5.0.3 on 2024-05-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0004_total_totalbhus'),
    ]

    operations = [
        migrations.AddField(
            model_name='poultry',
            name='totalDead',
            field=models.IntegerField(default=0),
        ),
    ]
