# Generated by Django 5.0.3 on 2024-05-07 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0004_alter_poultry_poultryname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(upload_to='images/')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('TotalChickenFeed', models.IntegerField()),
                ('totalMedicine', models.IntegerField()),
                ('totalBhus', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('totalVaccine', models.IntegerField()),
                ('poultryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userhome.poultry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
