# Generated by Django 5.0.3 on 2024-08-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0006_deadinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
