# Generated by Django 5.0.3 on 2024-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0006_remove_poultry_id_poultry_poultryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poultry',
            name='poultryId',
        ),
        migrations.AddField(
            model_name='poultry',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
