# Generated by Django 5.0.3 on 2024-08-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0008_deadinfo_deaddesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadinfo',
            old_name='deaddesc',
            new_name='description',
        ),
    ]
