# Generated by Django 5.0.3 on 2025-03-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0010_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Mail',
        ),
    ]
