# Generated by Django 5.0.3 on 2025-03-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0013_remove_notification_user_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='users',
        ),
    ]
